# Generated by Django 4.1.6 on 2023-03-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wlosy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie', models.CharField(max_length=200)),
                ('odp1', models.CharField(max_length=100)),
                ('odp2', models.CharField(max_length=100)),
                ('odp3', models.CharField(max_length=100)),
                ('odp4', models.CharField(max_length=100)),
            ],
        ),
    ]
