# Generated by Django 4.1.6 on 2023-03-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_wstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wstep',
            name='waga',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='wstep',
            name='wiek',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='wstep',
            name='wzrost',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
