# Generated by Django 4.1.6 on 2023-06-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_dane'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dane',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Wlosy',
        ),
        migrations.DeleteModel(
            name='Wstep',
        ),
    ]
